[package]
name = "rust-qr-code"
version = "0.1.0"
edition = "2024"

[dependencies]

ffmpeg-next = "7.1.0"
glob = "0.3.2"
image = "0.25.6"
luma = "0.1.0"
qrcode = "0.14.1"
rgb = "0.8.50"
rqrr = "0.9.3"

xz = "0.1.0"
